# Generated by Django 3.2 on 2021-05-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gb_status', models.CharField(choices=[('UP', 'Upcoming'), ('SKIP', 'Skipped'), ('WAIT', 'Waiting'), ('REC', 'Received'), ('CANCEL', 'Canceled')], max_length=20)),
                ('gb_type', models.CharField(choices=[('KB', 'Keyboard'), ('KC', 'Keycaps'), ('ART', 'Artisan'), ('CB', 'Cables')], max_length=20)),
            ],
        ),
    ]
