# Generated by Django 3.2 on 2021-08-21 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupbuys', '0004_auto_20210524_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='gb_type',
            field=models.CharField(choices=[('KB', 'Keyboard'), ('KC', 'Keycaps'), ('ART', 'Artisan'), ('CB', 'Cables'), ('SW', 'Switches')], max_length=20),
        ),
    ]
